### ISSUE TITLE
Clickable links

### ISSUE THREAD

**Issue by ys-chung** [hideki0403/twitter-activitypub-bridge#1]
Thank you for your hard work on this project, it has been a valuable tool.

I have noticed currently using Mastodon web, I cannot click links in posts relayed by the bridge, I have to copy and open them in a browser. I would much appreciate if they are made clickable.

Thanks again for your time and effort 🙏

**Comment by hideki0403** [comment]
Thanks for reporting the issue with not being able to click on the link.
In addition to the above issue, we've fixed the hashtags and mentions so they work too!
